### ISSUE TITLE
Two arguments for --native-arg doesn't work

### ISSUE THREAD

**Issue by grzanka** [garstka/idact#10]
I would like to provide `-p plgrid-bigmem -A intdata` as native args, but it doesn't work:

```
→ idact-notebook pro --nodes 1 --cores 1 --memory-per-node 200GiB --walltime 0:14:00 --native-arg -p plgrid-bigmem -A intdata                    

Usage: idact-notebook [OPTIONS] CLUSTER_NAME
Try "idact-notebook --help" for help.

Error: no such option: -A
```

**Comment by garstka** [comment]
The way to do that would be:

```
--native-arg -p plgrid-bigmem --native-arg -A intdata
```

Perhaps it could be made more clear in the help string.

Also, if you mostly use a single account, you can use --save-defaults, so you don't have to type it in every time.

**Comment by garstka** [comment]
Help string changed: b7ebe24757c61e681383bb7e3145958d40976ef1

**Comment by grzanka** [comment]
It works as you suggested. Thanks for updating help string !

**Comment by garstka** [comment]
No problem.
