### ISSUE TITLE
Rozszerzenie biblioteki - projekt inżynierski

### ISSUE THREAD

**Issue by kapiekarz** [garstka/idact#14]
Jestem w zespole, który jako projekt inżynierski kontynuuje pracę nad idactem. Chcemy poprosić o dostęp do repozytorium, są dwie opcje: fork albo przeniesienie kodu do organizacji na GitHubie.

**Comment by garstka** [comment]
Please you English next time.
/
Proponuję fork + pull request do code review: [CONTRIBUTING.md](https://github.com/garstka/idact/blob/master/CONTRIBUTING.md)
Jest to zdrowa i częsta praktyka dla projektów open-source.
